### ISSUE TITLE
Production Issue and /Product page issue

### ISSUE THREAD

**Issue by lindsaymshepard** [susanBuck/e2-fall19#72] opened 2019-11-06 21:11 UTC
I have followed all the steps in the videos and unfortunately it is not loading on my production server- instead it is showing my "Hello from Digital Ocean" page. 

Also, locally, it is not opening the product page- it shows it routing to the product page in the url but stays on the main home page. 

Not sure where to start to get help with either!

**Comment by susanBuck** [comment] 2019-11-06 21:35
__re: Not loading on production__
a. What URL can we visit to see what you're seeing?
b. Can you share the contents of your server's VirtualHosts config file (`/etc/apache2/sites-enabled/000-default.conf`)?
c. Can you run `service apache2 restart` to double check that your server was restarted after updating the VirtualHost config file.

__re: Not working locally__
I'm cloning your project locally now to test. Will follow-up shortly.

**Comment by susanBuck** [comment] 2019-11-06 21:41
I cloned your repo locally and was able to get your `zipfoods` working on my local server. This means it's not a code specific problem, but a setup problem. 

Can you share a screenshot of what you see locally?

**Comment by lindsaymshepard** [comment] 2019-11-06 22:07
Was able since then to get it up on zip foods.lindsayshepard.me but it only loads the homepage and not the other pages- so it's the same as local.

All I see after clicking the product button on the home page for both local and on my production server is the url changes to /product at the end, but just routes back to the home page

<img width="371" alt="Screen Shot 2019-11-06 at 5 06 50 PM" src="https://user-images.githubusercontent.com/54860077/68342103-dc1b1900-00b7-11ea-9cb0-37db243c9d6c.png">

**Comment by susanBuck** [comment] 2019-11-06 22:13
Taking a closer look at your routes file, it looks like the route `/products` is invoking the `index` method in `AppController`:

```php
return [
    '/' => ['AppController', 'index'],
    '/contact' => ['AppController', 'contact'],
    '/products' => ['AppController', 'index'],
    '/product' => ['AppController', 'show'],
    '/about' => ['AppController', 'about'],
];
```

Note how both the `/` and `/products` route invoke this `AppController` / `index`. That's why you see the same thing when you go to both these routes.

[Compare that to my example where `/products` invokes `ProductController` / `index`.](https://github.com/susanBuck/e2/blob/master/zipfoods/routes.php#L6)

**Comment by lindsaymshepard** [comment] 2019-11-07 14:13
I made the changes to the route file from AppController to ProductController. It's now routing to a new page, except the page is blank. It doesn't give a 404 error message but it also is not giving the pages I created in the steps of the rest of the video.

**Comment by susanBuck** [comment] 2019-11-07 16:34
FYI - Looking at your code now - will follow-up shortly.

**Comment by susanBuck** [comment] 2019-11-07 17:22
Here's what I saw when trying to view your products page locally:
![image](https://user-images.githubusercontent.com/237711/68408198-edfdca00-0152-11ea-8a7e-8dab727cf1c5.png)

The error indicates:

```
Fatal error: Uncaught Error:  in /Users/Susan/Sites/hes/dwa-bash/students/e2/zipfoods/app/Controllers/ProductController.php:5 
```

Here's the top of your `ProductController`:

```php
<?php

namespace App\Products;

class ProductController extends ProductController
{
```

The error indicates it's on line 5: `class ProductController extends ProductController`

It says: `Class 'App\Products\ProductController' not found`

The issue is you've set the namespace to `namespace App\Products;`
As a result, it's trying to find the class at `'App\Products\ProductController`
But there is no corresponding `/app/Products/ProductController.php`
The actual file is at `/app/Controllers/ProductController`
So the namespace should be `namespace App\Controllers;` (like how it is in the provided AppController)

The next issue is with how the class is defined:
```php
class ProductController extends ProductController
```

This should be:

```php
class ProductController extends Controller
```

After resolving the above issues, I then get this error:

```
Fatal error: Uncaught Error: Call to a member function getAll() on null in /Users/Susan/Sites/hes/dwa-bash/students/e2/zipfoods/app/Controllers/ProductController.php:18
```

This screenshot explains the problem:
![image](https://user-images.githubusercontent.com/237711/68408951-497c8780-0154-11ea-91f9-379101646831.png)

Both your declaration of `_construct` and invocation of `parent::_construct($app);` need to be fixed so that the construct is prefixed with **two** underscores ([ref](https://hesweb.dev/e2/notes#/php/oop?jump=constructor-method)).

After fixing the above, the next error that revealed itself:

```
Fatal error: Uncaught Error: Class 'App\Controllers\Products' not found in /Users/Susan/Sites/hes/dwa-bash/students/e2/zipfoods/app/Controllers/ProductController.php:12
```

The problem is in this line:

```php
$this->products = new Products($this->app->path('database/products.json'));
```

Here you're invoking the `Products` class, but its namespace was never imported. We can fix this by adding a [use statement](https://hesweb.dev/e2/notes#/php/namespacing?jump=codeusecode-operator) at the top of the file.

After fixing that, the next error was:

```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: syntax error, unexpected end of file in /Users/Susan/Sites/hes/dwa-bash/students/e2/zipfoods/cache/8082cab19d4c6c17c208fd3db1208c0a877cc781.php:19 Stack trace: #0 /Users/Susan/Sites/hes/dwa-bash/students/e2/zipfoods/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\View\Engines\PhpEngine->evaluatePath('/Users/Susan/Si...', Array) #1 /Users/Susan/Sites/hes/dwa-bash/students/e2/zipfoods/vendor/illuminate/view/View.php(142): Illuminate\View\Engines\CompilerEngine->get('/Users/Susan/Si...', Array) #2 19
[...etc...]
```

This error is a bit obscure, because it's pointing to an issue in the cache directory, and I haven't yet talked about how to read this particular kind of error (I will next week). However, from the error message we see several references to "View" so this is a clue that the problem is likely in your view file. (The reason it's not pointing to the specific View file is because our blade view files are compiled into cached versions for display.)

I opened up `/views/products/index.blade.php` and found a typo on line 18... `@endreach` should be `@endforeach`. Note how in the code editor the pattern of the syntax highlighting seems off - this is a good hint that there's a problem somewhere in the code:

![image](https://user-images.githubusercontent.com/237711/68409453-1c7ca480-0155-11ea-8dd5-0c577b887a2e.png)

Once I fixed that, my auto-formatter indented things really oddly, which is another indicator that something is wrong/missing:

![image](https://user-images.githubusercontent.com/237711/68409609-62d20380-0155-11ea-8c8e-a4a8dc70879a.png)


Line 14 is missing a closing `>`:
```html
<a href='/product?id={{ $product['id'] }}'
```

Also, because single quotes are used to surround the value for the `href` attribute, we should switch to double quotes within the blade expression. Otherwise it terminates the `href` string prematurely.

The corrected line should look like this:
```html
<a href='/product?id={{ $product["id"] }}'>
```

Other issues:

Line 17 is missing a closing `>`:
```php
<img class='product-thumb' src="/images/products/{{ $product['id'] }}"
```

There's no closing `</div>` for the div that starts on line 15.
There's no closing `</a>` for the link that starts on line 14.
There's no closing `</div>` for the div that starts on line 11.

After fixing the above points, my code looked like this:

![image](https://user-images.githubusercontent.com/237711/68409974-03c0be80-0156-11ea-83be-5e86eea01a35.png)

At this point, everything looked correctly indented and there didn't appear to be any issues with the syntax highlighting, so I tested it in the browser. The page loaded, but there were still some bugs:

![image](https://user-images.githubusercontent.com/237711/68410074-218e2380-0156-11ea-899c-2f240d6accc1.png)

The error indicates there's no `$product` variable, so I took a closer look at your for loop and discovered the cause.

```php
@foreach ($products as $products)
```

Should be
```php
@foreach ($products as $product)
```

Tested again, and this time no errors, but the images weren't displaying:

![image](https://user-images.githubusercontent.com/237711/68410182-51d5c200-0156-11ea-9f97-284847207648.png)

I looked at the `public` directory and noted there was no `/public/images/products` directory. Instead, it was nested within a `zipfoods-assets-master` directory.

![image](https://user-images.githubusercontent.com/237711/68410231-69ad4600-0156-11ea-86d4-a3ab5fbe915c.png). 

I re-arranged things so it looked like this:

![image](https://user-images.githubusercontent.com/237711/68410390-a4af7980-0156-11ea-88d8-9f7a08a3a800.png)

After a refresh, the images were still broken, so I took a closer look at the line in the code that displays the images:

```html
<img class='product-thumb' src="/images/products/{{ $product['id'] }}">
```

Here I discovered it was missing the image extension (`.jpg`). It should be:

```html
<img class='product-thumb' src="/images/products/{{ $product['id'] }}.jpg">
```

![image](https://user-images.githubusercontent.com/237711/68410501-d1639100-0156-11ea-85e7-826d3cef99e4.png)


Now the product images were loading, but the logo was broken.

Looking at your master template, I see it was because it was attempting to load  it from that `zipfoods-assets-master` directory which I reorganized out in the above step:

```html
<img id='logo' src='/zipfoods-assets-master/images/zipfoods-logo.png' alt='Logo'>
```

To fix, I corrected the path:

```html
<img id='logo' src='/images/zipfoods-logo.png' alt='Logo'>
```

And now everything loaded as expected:

![image](https://user-images.githubusercontent.com/237711/68410663-1687c300-0157-11ea-96ee-e338b8683f53.png)

## Conclusion
Whew! I know these are a lot of details but I hope the step-by-step walk-through of how I debugged things is useful.

I think the common theme with all the bugs is this: *details*. You didn't have any major logic issues, it was all just little details.

I suspect you're building a lot of your code by typing it out from scratch. This may seem like the best way to learn, but it can actually be really problematic in the beginning because when we're not yet comfortable in the little details (all the brackets, quotes, etc.) we make mistakes, and we're not yet trained/fluent in seeing those mistakes.

So instead of typing things out from scratch, I suggest a "copy, paste, edit, test, repeat" approach.

Copy code you know is working - pull from my examples in the notes, or the code repository I share.

Then, make *small* edits to customize. And with each step, confirm your changes are working. If they're not, undo what you just did, get it back to a working state, and then try again.

It can be a painstaking process, but this is how we learn, and train ourselves to see the details. With time, as we grow more comfortable with the details, then we transition into writing more things "from scratch". 

But the copy/paste/edit/test/repat approach never really goes away. To this day, if I'm working with something new or something I'm having a hard time getting to work, I'll start with a working example of someone else's code and dissect/edit it until it's working and doing what I want.

And, as I always emphasize in lecture, it's all about **incremental development**. The above debugging process I shared showed a lot of errors that needed to be resolved before the page would load. An incremental development process would never result in so many errors, because you would be finding them/resolving them as you go.

This was a long winded answer, but I hope it was useful.  Coding can be extremely frustrating, but once you learn some effective strategies to work with it, it becomes more of a fun puzzle then a tangled mystery. (Sometimes :-)

**Comment by lindsaymshepard** [comment] 2019-11-07 18:06
Wow thank you so much! I definitely was typing things out to learn instead of copy and pasting things, but will do that in the future since clearly I had a lot of bugs. Thank you for taking the time to go through everything for me.

**Comment by lindsaymshepard** [comment] 2019-11-07 18:22
I was able to fix everything except still struggling with the use statement- what exactly does it need to include?

**Comment by susanBuck** [comment] 2019-11-09 00:42
Should be:

```php
use App\Products;
```

Because if we look at Products.php its namespace is:

```php
namespace App;
```

**Comment by baugh20s** [comment] 2019-11-12 01:44
I'm getting one of the same errors as above, the one about an undefined variable. However, I think I have the foreach loop correct.

This is what comes up on my products page:

Notice: Undefined variable: products in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php on line 13

Notice: Undefined variable: products in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php on line 20

And this is what comes up on my product?id page:


Notice: Undefined variable: products in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php on line 13

Fatal error: Uncaught Error: Call to a member function getById() on null in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php:29 Stack trace: #0 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(81): App\Controllers\ProductController->show() #1 /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/public/index.php(15): E2\App->route() #2 {main} thrown in /Applications/XAMPP/xamppfiles/htdocs/e2/zipfoods/app/Controllers/ProductController.php on line 29

I'm not sure how to interpret these errors - they could all stem from the same cause, but I've combed through the video and notes and wasn't able to find an issue with what I have. Any hints would be appreciated!

**Comment by susanBuck** [comment] 2019-11-12 03:08
Hi @baugh20s - 

Looks like a little typo/gotcha on line 13 and 20 in your [ProductController](https://github.com/baugh20s/e2/blob/master/zipfoods/app/Controllers/ProductController.php).

This:
```php
$this->$products 
```

Should be:

```php
$this->products 
```

**Comment by baugh20s** [comment] 2019-11-13 00:08
Thank you!

**Closed** 2019-11-13 01:36 UTC
