### ISSUE TITLE
p3 stopped deploying

### ISSUE THREAD

**Issue by janenycxo** [susanBuck/e2-fall19#39] opened 2019-10-13 08:55 UTC
Hello Classmates....

I started the project and it deployed on p3, but i wanted to improve on it so i made some revisions. During the process, apache would not restart (fixed that...accidently left out a bracket in vhosts) and could not pull from github to DigitalOcean (merge issue from branch master which was resolved), then after all issues, p3 still would not deploy. 

I went back to my last commit when the page deployed and it didn't seem to do it. 

As a last resort, I referenced to class notes and made sure all the codes looked similar before again committing, and restarting apache. I thought it would work this time, but my p3 is still not deploying. 

What are some reasons why a page would not deploy? php code? I mirrored the professor's notes. host conflict? i already tried that. I am going to keep plugging away but I welcome any suggestions, perhaps I missed something or haven't tried something else. Penny for your thoughts....

Jane

**Comment by Matt49** [comment] 2019-10-14 10:10
Hi Jane,

You probably have done this, but did you restart your production server? I couldn't tell from your description if that's what you meant by "restart apache" or if you were just referring to your local server.

-Matt

**Comment by susanBuck** [comment] 2019-10-14 15:52
http://p3.janenycxo.me is working as of this writing. 

Do you know what fixed it?

**Comment by janenycxo** [comment] 2019-10-14 18:36
> Hi Jane,
> 
> You probably have done this, but did you restart your production server? I couldn't tell from your description if that's what you meant by "restart apache" or if you were just referring to your local server.
> 
> -Matt

Apache failed to restart because I accidentally left out a closed bracket. It works now.

**Comment by janenycxo** [comment] 2019-10-14 18:39
I believe it may have been the vhost config file because once I got Apache restarted the page deployed. During this time I practiced on the local server and the page info pops up. Now I’m working on trying to get the form results to direct back and populate to index.php.

**Comment by susanBuck** [comment] 2019-10-15 15:42
Will close this thread out since the issue is resolved - but feel free to start another thread if you're still stuck on passing the results back to index.php. 👍

**Closed by susanBuck** 2019-10-15 15:42 UTC
