### ISSUE TITLE
XAMPP Installation Location

### ISSUE THREAD

**Issue by shcantrell** [susanBuck/e2-fall19#7] opened 2019-09-13 04:38 UTC
Hello,

I was having administrative access issues that were preventing me from editing the hosts file in rerouting the `Practice.loc` domain.

I realized later I could use Cmder in "run in administrator" mode that may have prevented this and I will now continue using that mode.

Before I realized this, I decided to address the issue by reinstalling my xampp in a directory in the C: drive that offered administrative access; the `Support` folder. Everything is working as expected now since I did that (at least, up to Part 5 of this week's lessons).

Subsequently, my xampp and root folder has a new path, which differs from what is referenced in our lectures: `C:/Support/xampp/htdocs`. 

Will this new path be acceptable or are there future issues I will run into, due to it?

It did resolve the conflict the localhost had in using port 80. My first install required me to reassign that port.

Thanks,
Susan Cantrell

**Comment by susanBuck** [comment] 2019-09-13 11:23
Hi @shcantrell 

I don't anticipate it causing any future problems with an alternative XAMPP installation path.

I am curious though - the command I provided was prefixed with `elevate` which should have opened the file with admin rights:

```
elevate nano c:\Windows\System32\drivers\etc\hosts
```

Curious if you used elevate when you initially tried to edit the hosts file, and if so, did it fail/report an error? (Just trying to understand if the instructions I provided are failing at some point :).

**Comment by shcantrell** [comment] 2019-09-16 00:17
Hello, @susanBuck 

Okay...here I go.

Do know that my laptop is issued by my workplace and I am certain a variety of permissions are blocked, but I am unsure which ones they are, exactly.

I did use the `elevate nano c:\Windows\System32\drivers\etc\hosts` command in my initial setup. It seemed to work just fine without any error messages or indications there were any problems.

After restarting Apache, I went to check `http://practice.loc` and an error message was returned stating, "This site can't be reached."

That prompted me to double-check all my changes again using `cat` to view all changed files and everything looked accurate. I stopped and started Apache several times to make sure it reset itself. Still, the local domain gave me the error message.

I then proceeded to remove all of my changes, saving the files in their original codes and reentered the changes again. I restarted Apache and checked the local domain, which still had the error message. I did this over and over again.

The next thing I did was look into my Apache error logs, but the most recently logs showed transactions that occurred 20 mins. prior and more current logs were not written. The older logs read,

`[Fri Sep 13 00:21:18.565100 2019] [ssl:warn] [pid 12012:tid 708] AH01909: www.example.com:443:0 server certificate does NOT include an ID which matches the server name`

which I gathered was the obvious problem of the local domain not being remapped.

I then looked more carefully at the display window of XAMMP, and saw this message: `You are not running with administrator rights! This will work for most application stuff but whenever you do something with services about running this application with administrator rights!` It was in black print, so did not draw my attention earlier. That was when I thought permissions was definitely a culprit in this issue.

Through the `cat` command, I saw that the remapping information was made to the `hosts` file, but started to wonder if it was not truly engaging, somehow. So, I decided to open the `hosts` file in another application (Notepad++) to confirm the remapping information was there.

In Notepad++, the remapping information was present. Nevertheless, I deleted it and entered the remapping information again, and this time, did get a warning message that I was not running Notepad++ "as an administrator" when I wanted to save the file.

This is when it dawned on my that maybe I needed to run Cmder (and all other apps) as an administrator. After restarting Notepad++ in "as an administrator" mode, I repeated my steps and was able to save the file.

I restarted Apache for the nth time, but this time, Apache would not restart. There was an error message in red reading, `Error: Apache shutdown unexpectedly. This may be due to a blocked port, missing dependencies, improper privileges, a crash, or a shutdown by another method."

I believed I tried to delete and reenter all changes again, but Apache would not restart anymore, regardless.

After this, I had no clues as to why things were going so awry. The best deduction I could make was the lack of permissions may be allowing certain things and not others to execute, creating inconsistencies with performance.

I have been informed by my workplace that if I ever needed to install something, I could use the `Support` directory, which has a range of permissions granted to it. That is why I finally went that route.

After the new install onto the `Support` directory, I did notice that I did not have to change the `hosts` file again (since it was not part of the XAMPP reinstall) and the local domain worked just fine this time. Again, I also did not have to reassign the localhost's port and it is pointing to its default,  localhost:80.

For a brief moment, I considered removing everything from my `Support` directory and starting over from scratch just to see if I could duplicate the original error or if I would be successful this time. But, for the sake of moving forward with the lectures, I decided not to do so.

I could though, if you wanted me to.

So - where did I go so wrong?! :)

Thanks,
Susan Cantrell

**Comment by lkratzberg** [comment] 2019-09-16 00:33
I am also using a work-issued computer. I have never had any issues with not being able to do things due to administrative privileges, until this. Once I ran Cmdr as an administrator, I was able to update the hosts file and everything is fine now. 

Thanks for the tip :)

**Comment by shcantrell** [comment] 2019-09-16 01:06
@lkratzberg - awesome!

**Comment by susanBuck** [comment] 2019-09-19 00:18
@shcantrell Thanks for the thoughtful notes on your process! 

To recap/summarize my understanding - Apache was starting fine, but your local domain was not resolving. You got a message similar to this:

![image](https://user-images.githubusercontent.com/237711/65197018-921a9d00-da4f-11e9-830c-9a6ad7b6058f.png)

This message will happen if your `hosts` file does not have an appropriate mapping for the local domain you're trying to use.

But you double checked your hosts file and confirmed the mapping was there.

It could also happen if your `hosts` file was corrupt ([reference](https://superuser.com/questions/1191172/osx-sierra-hosts-file-is-ignored)). 

I'm wondering if somehow it did get corrupt, and when you rebuilt it in Notepad++ you fixed it without realizing it.

Other notes:

FYI: The XAMPP message in the console about administrator rights is actually normal, and not an indication of a problem. I get the same message with Apache started:
```
You are not running with administrator rights! This will work for
4:59:56 PM  [main] 	most application stuff but whenever you do something with services
4:59:56 PM  [main] 	there will be a security dialogue or things will break! So think 
4:59:56 PM  [main] 	about running this application with administrator rights!
```

(Can totally see why this would lead you down the permissions trail though...)

It's hard to say for sure what actually fixed your problem, but kudos to you for sticking with it and getting it sorted out!

**Closed by susanBuck** 2019-09-19 00:18 UTC

**Comment by shcantrell** [comment] 2019-09-20 00:17
thanks.
