### ISSUE TITLE
XAMMP config not opening - Week 2 Part 2

### ISSUE THREAD

**Issue by anyav77** [susanBuck/e2-fall19#22] opened 2019-09-18 00:54 UTC
My XAMMP interface looks different than the video.  When I click the config button and select apache httpd.config, nothing happens.  It looks like the program attempts to open the file for a blink of a sec, but it doesn't open.

Is it ok to edit it in Notepad instead?
![screenshot - xamp config not working](https://user-images.githubusercontent.com/1045307/65094992-34fde900-d974-11e9-8e0b-66165804e861.png)

**Comment by susanBuck** [comment] 2019-09-18 16:34
Hi @anyav77 -

Yup, it's okay to manually open the apache config file (`c:\xampp\apache\conf\httpd.conf`) in Notepad and edit it there. 

I'm not sure why it won't open for you from the XAMPP interface. For some low-hanging-fruit-troubleshooting I'd try restarting XAMPP and/or your computer and see if that helps.

**Comment by anyav77** [comment] 2019-09-23 03:30
I tried restarting it, but it didn't help.  Are there any other troubleshooting steps I could take?
I'm unsure whey the interface of my XAMPP is different than the video.  Is it a version difference, or I'm not opening it correctly?

**Comment by susanBuck** [comment] 2019-09-23 16:07
Are any of the other Apache-related config files listed in the dropdown opening (e.g. PHP php.ini)? What about the MySQL config files?

If we can determine that *all* config files fail to open, there's probably some issue/disconnect between XAMPP and your default text editor.

Out of curiosity, if you find the Apache config file via your File Explorer and right click it and choose _Properties_, what program is it set to open with? For example, in my screenshot below it says my config file is open using Notepad.

![image](https://user-images.githubusercontent.com/237711/65442659-93a2e700-ddfa-11e9-9270-d4396840c5b4.png)


**Re: version differences** - for reference, I'm running **v3.2.4 [Compiled June 5th 2019]**.

**Comment by susanBuck** [comment] 2019-09-23 16:19
On a related note - also look in your XAMPP config and see what your default editor is set to. In the screenshot below you can see mine is set to `notepad.exe`

![image](https://user-images.githubusercontent.com/237711/65443567-57708600-ddfc-11e9-8c7b-1b005a0cf508.png)

**Comment by shcantrell** [comment] 2019-09-23 23:37
@anyav77 
Since you mentioned having a totally differently UI, maybe you downloaded a totally different version of XAMPP than was recommended in the lecture.

What our notes said: "Download xampp-win32-7.3.1-0-VC15-installer.exe."

Could this be the case?

**Comment by anyav77** [comment] 2019-09-24 21:12
All the config files fail to open in XAMPP.  
httpd.config defaults to Notepad.
When I go to C:\xampp\apache in Window explorer, I'm unable to see httpd.conf 
When I search for httpd.config, it shows in the search results.
When I select "Open file location", I'm able to see the file in Window Explorer.

![apache-conf missing](https://user-images.githubusercontent.com/1045307/65550791-3def3d00-ded5-11e9-96a7-b99791c2feab.png)
![apache-conf found](https://user-images.githubusercontent.com/1045307/65550803-46e00e80-ded5-11e9-9f3f-054cc9b858fa.png)
![apache-conf visible](https://user-images.githubusercontent.com/1045307/65550819-4cd5ef80-ded5-11e9-9d4a-0cfeece5f5fe.png)

**Comment by susanBuck** [comment] 2019-09-25 02:25
> When I go to C:\xampp\apache in Window explorer, I'm unable to see httpd.conf

You need to go one directory deeper, into `conf`:

Full path: `C:\xampp\apache\conf\httpd.conf`.

I'm stumped on why XAMPP won't open the files for you. It's not a problem I've seen reported before, and my Google searches for clues/other users reporting the issue is turning up dry.

You could try re-installing XAMPP?

Other than that, the key thing is that you can access the files, you just have to do it manually. Because these are not files that you need to access frequently, this shouldn't be too big of a hindrance. 

Sorry I don't have a better answer. : \

**Comment by susanBuck** [comment] 2019-09-30 15:46
I'm going to close this thread out - @anyav77 Feel free to email me directly if you wish to troubleshoot this further.

**Closed by susanBuck** 2019-09-30 15:46 UTC
