### ISSUE TITLE
php console App fresh error in ssh root for p4

### ISSUE THREAD

**Issue by lindsaymshepard** [susanBuck/e2-fall19#107] opened 2019-12-11 15:55 UTC
root@e2:/var/www/html/e2/p4# php console App fresh
"Executing App\Commands\AppCommand@fresh"
PHP Fatal error:  Uncaught Error: Call to undefined method App\Commands\AppCommand::fresh() in /var/www/html/e2/p4/vendor/susanbuck/e2core/src/App.php:80
Stack trace:
#0 /var/www/html/e2/p4/console(12): E2\App->console(Array)
#1 {main}
  thrown in /var/www/html/e2/p4/vendor/susanbuck/e2core/src/App.php on line 80
root@e2:/var/www/html/e2/p4#

**Comment by lindsaymshepard** [comment] 2019-12-11 15:57
I am receiving this error when I try to run this on my production server 

APP_NAME='p4'
APP_URL='http://p4.lindsayshepard.me'

DB_HOST='localhost'
DB_NAME='p4'
DB_USERNAME='e2'
DB_PASSWORD='haneda16'

this is the contents of my .env file on production

**Comment by susanBuck** [comment] 2019-12-12 00:23
Hi @lindsaymshepard -

Just took a look at your repo and your [p4/app/Commands/AppCommand.php](https://github.com/lindsaymshepard/e2/blob/master/p4/app/Commands/AppCommand.php) file only has one method, `test`. There is no `fresh` method.

Is it possible you haven't sync'd changes from local?

**Comment by RGPhD** [comment] 2019-12-12 08:26
Hello @lindsaymshepard,
I was trying to view your AppCommand file and as Professor Buck mentions, you only have the ```test``` method.  You do not have the ```migrate```, ```seed``` or ```fresh``` method in your github file.  Maybe if your push your changes to github and then pull the changes to production you can narrow down the problem.
Robelyn

**Comment by lindsaymshepard** [comment] 2019-12-12 15:50
Yes unfortunately when I go to push the changes to git and pull the changes to digital ocean it says there are no changes to update.

**Comment by susanBuck** [comment] 2019-12-12 16:59
Hi @lindsaymshepard -

Let's run through some commands to figure out what's going on. Please share the output of the following commands with us.

First, locally, within your `p4` directory, run `git status`. This will tell us the current status of your repo locally - if any files have changed, if there any pending commits, etc.

Next, run `git log` to have it print out a log of recent commits. When you run this command, it shows you a certain amount of commits at a time, and whenever you hit enter, it'll show you more commits. We only need to see the most recent commits so you can hit `ctrl` + `z` to end the command. Then, you can copy the contents of the output to share here.

Finally, run `cat /app/Commands/AppCommand.php` to see the contents of your `AppCommand.php` file so we can confirm it has the `fresh` method.

**Comment by lindsaymshepard** [comment] 2019-12-12 18:59
LindsayShepard@Lindsays-MBP p4 % git status
On branch master
nothing to commit, working tree clean
LindsayShepard@Lindsays-MBP p4 % git log
commit 252d979dbd7e60d8869ae1a762f15c0d2b8a8c1a (HEAD -> master)
Author: Lindsay Shepard <lindsaymshepard@icloud.com>
Date:   Wed Dec 11 10:39:40 2019 -0500

    Initial database setup
LindsayShepard@Lindsays-MBP p4 % cat /app/Commands/AppCommand.php
cat: /app/Commands/AppCommand.php: No such file or directory
LindsayShepard@Lindsays-MBP p4 % cd /app/Commands/AppCommand.php
cd: no such file or directory: /app/Commands/AppCommand.php

**Comment by RGPhD** [comment] 2019-12-12 21:30
Dear @lindsaymshepard,
You have two folders setup for p4.  Which one are you using for your P4 project,
<https://github.com/lindsaymshepard/e2/tree/master/MyApp> or <https://github.com/lindsaymshepard/e2/tree/master/p4>?
Robelyn

**Comment by lindsaymshepard** [comment] 2019-12-12 22:32
I am using the p4 one. not the MyApp one.

**Comment by RGPhD** [comment] 2019-12-12 22:39
Hi Lindsay,
Once, I received the same error message ```nothing to commit, working tree clean```, when I knew had changes to commit.  I am not sure if it is correct protocol, but I made a small change to the file I wanted to push to GitHub and pull to production.  I was then able to update my files accordingly.
Robelyn

**Comment by janenycxo** [comment] 2019-12-12 23:35
I am also getting an error when I enter : php console App fresh

root@e2fall2019:/var/www/html/e2/p4# php console App seed
PHP Parse error:  syntax error, unexpected 'dump' (T_STRING), expecting ';' or '{' in /var/www/html/e2/p4/app/Commands/AppCommand.php on line 7

This is what i have on my line 7 - dump('It works! You invoked your first command.');
I then deleted the line and tried again, with the same response.

**Comment by susanBuck** [comment] 2019-12-12 23:47
Hi @janenycxo,

There's a syntax error in your file.

The `dump` statement is located before the starting `{` bracket of the `test` method.

![image](https://user-images.githubusercontent.com/237711/70758030-9fbe8680-1d0f-11ea-924b-955aaadc0bfa.png)

Compare that to [my AppCommand file](https://github.com/susanBuck/e2/blob/master/zipfoods/app/Commands/AppCommand.php#L10) for reference.

**Comment by janenycxo** [comment] 2019-12-13 01:42
Hi Professor,

The same e2 user and password remained unchanged but the error appears to be a password/database issue. 

I updated the codes on AppCommands and get this new error-

root@e2fall2019:/var/www/html/e2/p4# php console App migrate
"Executing App\Commands\AppCommand@migrate"
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'e2'@'localhost' (using password: YES) in /var/www/html/e2/p4/vendor/susanbuck/e2core/src/Database.php:22
Stack trace:
#0 /var/www/html/e2/p4/vendor/susanbuck/e2core/src/App.php(100): E2\Database->__construct('127.0.0.1', 'p4', 'e2', 'janeyehr', 'utf8mb4')
#1 /var/www/html/e2/p4/app/Commands/AppCommand.php(17): E2\App->db()
#2 /var/www/html/e2/p4/vendor/susanbuck/e2core/src/App.php(80): App\Commands\AppCommand->migrate()
#3 /var/www/html/e2/p4/console(12): E2\App->console(Array)
#4 {main}
  thrown in /var/www/html/e2/p4/vendor/susanbuck/e2core/src/Database.php on line 22
root@e2fall2019:/var/www/html/e2/p4# php console App seed
"Executing App\Commands\AppCommand@seed"
root@e2fall2019:/var/www/html/e2/p4# php console App fresh
"Executing App\Commands\AppCommand@fresh"
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'e2'@'localhost' (using password: YES) in /var/www/html/e2/p4/vendor/susanbuck/e2core/src/Database.php:22
Stack trace:
#0 /var/www/html/e2/p4/vendor/susanbuck/e2core/src/App.php(100): E2\Database->__construct('127.0.0.1', 'p4', 'e2', 'janeyehr', 'utf8mb4')
#1 /var/www/html/e2/p4/app/Commands/AppCommand.php(17): E2\App->db()
#2 /var/www/html/e2/p4/app/Commands/AppCommand.php(60): App\Commands\AppCommand->migrate()
#3 /var/www/html/e2/p4/vendor/susanbuck/e2core/src/App.php(80): App\Commands\AppCommand->fresh()
#4 /var/www/html/e2/p4/console(12): E2\App->console(Array)
#5 {main}
  thrown in /var/www/html/e2/p4/vendor/susanbuck/e2core/src/Database.php on line 22
root@e2fall2019:/var/www/html/e2/p4#

**Comment by janenycxo** [comment] 2019-12-13 01:47
mysql> show grants for root@localhost;
+---------------------------------------------------------------------+
| Grants for root@localhost                                           |
+---------------------------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' WITH GRANT OPTION |
| GRANT PROXY ON ''@'' TO 'root'@'localhost' WITH GRANT OPTION        |
+---------------------------------------------------------------------+
2 rows in set (0.00 sec)

mysql> SELECT User, Host, HEX(authentication_string) FROM mysql.user;
+------------------+-----------+------------------------------------------------------------------------------------+
| User             | Host      | HEX(authentication_string)                                                         |
+------------------+-----------+------------------------------------------------------------------------------------+
| root             | localhost |                                                                                    |
| mysql.session    | localhost | 2A5448495349534E4F544156414C494450415353574F52445448415443414E42455553454448455245 |
| mysql.sys        | localhost | 2A5448495349534E4F544156414C494450415353574F52445448415443414E42455553454448455245 |
| debian-sys-maint | localhost | 2A31433334303331433435333635333945413133373144354130353534464534354130434231433646 |
| e2               | localhost | 2A30414231433943334246303730333033413241453642433230443833323930323831383545414434 |
+------------------+-----------+------------------------------------------------------------------------------------+
5 rows in set (0.01 sec)

**Comment by janenycxo** [comment] 2019-12-13 01:49
root@e2fall2019:/var/www/html/e2/p4# php console App fresh
"Executing App\Commands\AppCommand@fresh"
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'e2'@'localhost' (using password: YES) in /var/www/html/e2/p4/vendor/susanbuck/e2core/src/Database.php:22
Stack trace:
#0 /var/www/html/e2/p4/vendor/susanbuck/e2core/src/App.php(100): E2\Database->__construct('127.0.0.1', 'p4', 'e2', 'janeyehr', 'utf8mb4')
#1 /var/www/html/e2/p4/app/Commands/AppCommand.php(17): E2\App->db()
#2 /var/www/html/e2/p4/app/Commands/AppCommand.php(60): App\Commands\AppCommand->migrate()
#3 /var/www/html/e2/p4/vendor/susanbuck/e2core/src/App.php(80): App\Commands\AppCommand->fresh()
#4 /var/www/html/e2/p4/console(12): E2\App->console(Array)
#5 {main}
  thrown in /var/www/html/e2/p4/vendor/susanbuck/e2core/src/Database.php on line 22
root@e2fall2019:/var/www/html/e2/p4#

**Comment by janenycxo** [comment] 2019-12-13 02:02
mysql> show grants for e2@localhost;
+-------------------------------------------------+
| Grants for e2@localhost                         |
+-------------------------------------------------+
| GRANT ALL PRIVILEGES ON *.* TO 'e2'@'localhost' |
+-------------------------------------------------+
1 row in set (0.00 sec)

**Comment by susanBuck** [comment] 2019-12-13 17:21
Hi @janenycxo - 

Because this is an environment/production server related issue, it'd be helpful if I could log into your server and do some direct troubleshooting.

Could you follow [these instructions](https://hesweb.dev/e2/notes#/appendix/instructor-server-access) to give me server access?

**Comment by janenycxo** [comment] 2019-12-13 17:52
Hi Susan,
I have added the public key, thanks for helping troubleshoot!
Jane

**Comment by susanBuck** [comment] 2019-12-13 17:53
@janenycxo Great - I'm in! Checking things out now; will report back shortly.

**Comment by susanBuck** [comment] 2019-12-13 18:25
@janenycxo -

I logged in to your production server and confirmed your `p4` database existed, your `e2` MySQL user was created, and your `.env` file was set up correctly.

The only thing left to confirm you had the correct password for the `e2` user in your `.env` file.

Because the passwords are stored as encrypted values, I couldn't actually check that it was correct, but I could reset it to the value you were using in your `.env` file:

```
ALTER USER 'e2'@'localhost' IDENTIFIED BY 'your-password';
```

After I did that, I was able to run your DB commands:

```bash
root@e2fall2019:/var/www/html/e2/p4# php console App migrate
"Executing App\Commands\AppCommand@migrate"
"Migration complete."
```

So the cause was some disconnect between what the password was originally created as and what it was in the `.env` file. 

Go ahead and try running the commands on your end and let me know if you run into any more problems!

**Comment by janenycxo** [comment] 2019-12-13 19:04
Hi Susan,

I reset my password in SQL, and updated in the .env file. 

APP_NAME='Project 4'
APP_URL='http://p4.janenycxo.me'

DB_HOST='localhost'
DB_NAME='p4'
DB_USERNAME='e2'
DB_PASSWORD='janeyeh'

My home page displays an index (p4.janenycxo.me), while my local host (http://p4.localhost/) looks as it should.

Not sure why I am still getting an error though.

c:\xampp\htdocs\e2\p4 (master){hg}
λ php console App migrate
"Executing App\Commands\AppCommand@migrate"
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'e2'@'localhost' (using password: YES) in C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\Database.php:22
Stack trace:
#0 C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\App.php(100): E2\Database->__construct('127.0.0.1', 'p4', 'e2', 'janeyeh', 'utf8mb4')
#1 C:\xampp\htdocs\e2\p4\app\Commands\AppCommand.php(17): E2\App->db()
#2 C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\App.php(80): App\Commands\AppCommand->migrate()
#3 C:\xampp\htdocs\e2\p4\console(12): E2\App->console(Array)
#4 {main}
  thrown in C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\Database.php on line 22

Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1045] Access denied for user 'e2'@'localhost' (using password: YES) in C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\Database.php:22
Stack trace:
#0 C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\App.php(100): E2\Database->__construct('127.0.0.1', 'p4', 'e2', 'janeyeh', 'utf8mb4')
#1 C:\xampp\htdocs\e2\p4\app\Commands\AppCommand.php(17): E2\App->db()
#2 C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\App.php(80): App\Commands\AppCommand->migrate()
#3 C:\xampp\htdocs\e2\p4\console(12): E2\App->console(Array)
#4 {main}
  thrown in C:\xampp\htdocs\e2\p4\vendor\susanbuck\e2core\src\Database.php on line 22

**Comment by janenycxo** [comment] 2019-12-13 19:09
> I am using the p4 one. not the MyApp one.

Hi Lindsay,
Were you able to resolve the error you posted about?
Jane

**Comment by susanBuck** [comment] 2019-12-13 19:10
Hi @janenycxo -

It looks like now you're now working/debugging on your local server, per the path `c:\xampp\htdocs\e2\p4`. 

Note that the debugging/changes I described in my last post were on your production server.

Locally, in `.env` the `DB_NAME` should be `root` and the `DB_PASSWORD` should be blank, as these are the defaults that XAMPP's MySQL use.

**Comment by susanBuck** [comment] 2019-12-13 19:13
@janenycxo If you want to connect to debug this in real-time, my Zoom URL is https://zoom.us/meeting/6503342434. I'll be around for the next several hours.

**Comment by janenycxo** [comment] 2019-12-13 19:15
sounds good, I'll join zoom in about an hour....afterschool pick ups are happening right now.

**Comment by janenycxo** [comment] 2019-12-13 20:00
root@e2fall2019:/var/www/html/e2/p4# php console App migrate
"Executing App\Commands\AppCommand@migrate"
"Migration complete."
root@e2fall2019:/var/www/html/e2/p4#

**Comment by susanBuck** [comment] 2019-12-13 21:07
@janenycxo That usually happens if your VirtualHost is not pointing to the `/public` directory within the project.

Here's an example of what it should look like:
```
<VirtualHost *:80>
    ServerName zipfoods.yourdomain.com
    DocumentRoot /var/www/html/e2/zipfoods/public
    <Directory /var/www/html/e2/zipfoods/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        Require all granted
    </Directory>
</VirtualHost>
```

Note how the ServerName and DocumentRoot are both pointing to `/public` *within* the ZipFoods directory.

Because I have access to your server now, i was able to double check your VirtualHost config file : ) I saw this:

```
<VirtualHost *:80>
  ServerName p4.janenycxo.me
  DocumentRoot "/var/www/html/e2/p4"
  <Directory "/var/www/html/e2/p4">
    AllowOverride All
  </Directory>
</VirtualHost>
```

Note how it's *not* pointing to `/public` within `/var/www/html/e2/p4`.

Try fixing that and then restarting Apache (`service apache2 restart`).

Ref: https://hesweb.dev/e2/notes#/php/frameworks/deploy?jump=virtualhosts

**Comment by susanBuck** [comment] 2019-12-16 19:26
Closing this thread out, but if there are any new/pending issues, feel free to start a new thread!

**Closed by susanBuck** 2019-12-16 19:26 UTC
