### ISSUE TITLE
Error 500 on Zipfoods Production

### ISSUE THREAD

**Issue by nbandach** [susanBuck/e2-fall19#84] opened 2019-11-18 20:55 UTC
After adding Virtual Host in production I get 500 error...
![Screenshot 2019-11-18 at 21 44 58](https://user-images.githubusercontent.com/6833462/69093040-f5c04700-0a4d-11ea-9329-94135a20da94.png)
All looks fine in the server:
![Screenshot 2019-11-18 at 21 54 38](https://user-images.githubusercontent.com/6833462/69093082-096bad80-0a4e-11ea-9059-2edaa69d7d92.png)
Droplet is active and other projects are working.
Help would be highly appreciated

**Comment by susanBuck** [comment] 2019-11-18 21:04
Can you run through the steps described in the [troubleshooting section of Deploy to Production](https://hesweb.dev/e2/notes#/php/frameworks/deploy?jump=troubleshooting) and share the output?

Can you also copy and share the full contents of your 000-default.conf file? I don't see any issues in your screenshot, but I'd like to test your configs on my system to double check.

**Comment by nbandach** [comment] 2019-11-18 22:40
Last login: Mon Nov 18 11:19:37 on console

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Natalias-MacBook-Air:~ natbandach$ ssh root@104.248.204.1
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Nov 18 19:58:29 UTC 2019

  System load:  0.0               Processes:           99
  Usage of /:   9.5% of 24.06GB   Users logged in:     0
  Memory usage: 40%               IP address for eth0: 104.248.204.1
  Swap usage:   0%

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

52 packages can be updated.
0 updates are security updates.


*** System restart required ***
********************************************************************************

Welcome to DigitalOcean's One-Click LAMP Droplet. 
To keep this Droplet secure, the UFW firewall is enabled. 
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

In a web browser, you can view:
 * The LAMP One-Click Quickstart guide: http://do.co/lamp1804#start
 * Your LAMP website: http://104.248.204.1

On the server:
 * The default web root is located at /var/www/html
 * The MySQL root password is saved in /root/.digitalocean_password
 * Certbot is preinstalled. Run it to configure HTTPS. See
   http://do.co/lamp1804#enable-https for more detail.

For help and more information, visit http://do.co/lamp1804

********************************************************************************
To delete this message of the day: rm -rf /etc/update-motd.d/99-one-click
Last login: Wed Nov 13 01:17:10 2019 from 88.26.147.114
root@e2:~# ls
root@e2:~# cd /var/www/html/e2
root@e2:/var/www/html/e2# apt install php7.2-mbstring
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php7.2-mbstring is already the newest version (7.2.24-0ubuntu0.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 52 not upgraded.
root@e2:/var/www/html/e2# sudo a2enmod rewrite
Module rewrite already enabled
root@e2:/var/www/html/e2# service apache2 restart
root@e2:/var/www/html/e2# git pull
Already up to date.
root@e2:/var/www/html/e2# cd zipfoods
root@e2:/var/www/html/e2/zipfoods# ls
README.md  cache          composer.lock  public      vendor
app        composer.json  config.php     routes.php  views
root@e2:/var/www/html/e2/zipfoods# chown -R www-data cache
root@e2:/var/www/html/e2/zipfoods# cat .gitignore
vendor
.env
root@e2:/var/www/html/e2/zipfoods# cp .env.example .env
root@e2:/var/www/html/e2/zipfoods# nano .env
root@e2:/var/www/html/e2/zipfoods# nano /etc/apache2/sites-enabled/000-default.conf
root@e2:/var/www/html/e2/zipfoods# service apache2 restart
root@e2:/var/www/html/e2/zipfoods# nano /etc/apache2/sites-enabled/000-default.conf
root@e2:/var/www/html/e2/zipfoods# nano /etc/apache2/sites-enabled/000-default.conf
root@e2:/var/www/html/e2/zipfoods# ls
README.md  cache          composer.lock  public      vendor
app        composer.json  config.php     routes.php  views
root@e2:/var/www/html/e2/zipfoods# nano /etc/apache2/sites-enabled/000-default.conf
root@e2:/var/www/html/e2/zipfoods# nano /etc/apache2/sites-enabled/000-default.conf
root@e2:/var/www/html/e2/zipfoods# service apache2 restart
root@e2:/var/www/html/e2/zipfoods# nano /etc/apache2/sites-enabled/000-default.conf
root@e2:/var/www/html/e2/zipfoods# service apache2 restart
root@e2:/var/www/html/e2/zipfoods# nano /etc/apache2/sites-enabled/000-default.conf
root@e2:/var/www/html/e2/zipfoods# service apache2 restart
root@e2:/var/www/html/e2/zipfoods# nano /etc/apache2/sites-enabled/000-default.conf
root@e2:/var/www/html/e2/zipfoods# 000-default.conf
000-default.conf: command not found
root@e2:/var/www/html/e2/zipfoods# nano 000-default.confx
root@e2:/var/www/html/e2/zipfoods# nano /etc/apache2/sites-enabled/000-default.conf

  GNU nano 2.9.3                    /etc/apache2/sites-enabled/000-default.conf                               

    AllowOverride All
  </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName zipfoods.natbandach.me
    DocumentRoot /var/www/html/e2/zipfoods/public
    <Directory /var/www/html/e2/zipfoods/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        Require all granted
    </Directory>
</VirtualHost>

Troubleshooting output:

root@e2:/var/www/html/e2/zipfoods# ll
total 100
drwxr-xr-x  7 root     root  4096 Nov 18 22:21 ./
drwxr-xr-x  8 root     root  4096 Nov 13 01:19 ../
-rw-r--r--  1 root     root   111 Nov 18 20:26 .env
-rw-r--r--  1 root     root    95 Nov 13 01:19 .env.example
-rw-r--r--  1 root     root    12 Nov 13 01:19 .gitignore
-rw-r--r--  1 root     root   448 Nov 13 01:19 README.md
drwxr-xr-x  3 root     root  4096 Nov 13 01:19 app/
drwxr-xr-x  2 www-data root  4096 Nov 13 01:19 cache/
-rw-r--r--  1 root     root   408 Nov 13 01:19 composer.json
-rw-r--r--  1 root     root 42506 Nov 13 01:19 composer.lock
-rw-r--r--  1 root     root   344 Nov 13 01:19 config.php
drwxr-xr-x  4 root     root  4096 Nov 13 01:19 public/
-rw-r--r--  1 root     root   102 Nov 13 01:19 routes.php
drwxr-xr-x 13 root     root  4096 Nov 13 01:23 vendor/
drwxr-xr-x  4 root     root  4096 Nov 13 01:19 views/
root@e2:/var/www/html/e2/zipfoods# cat .env
APP_NAME='Zipfoods'
APP_URL='http:/zipfoods.natbandach.me'

DB_NAME='myapp'
DB_USERNAME='root'
DB_USERNAME=''
root@e2:/var/www/html/e2/zipfoods# nano .env
root@e2:/var/www/html/e2/zipfoods# service apache2 restart
root@e2:/var/www/html/e2/zipfoods# cd /var/www/html/e2
root@e2:/var/www/html/e2# git pull
Already up to date.
root@e2:/var/www/html/e2# composer install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /var/www/html/e2
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
root@e2:/var/www/html/e2#

**Comment by susanBuck** [comment] 2019-11-18 23:00
I don't see any obvious issues from the above output.

The output of your `000-default.conf` contents appears truncated in the above post. If you're having difficulties copying the entire contents using nano, instead use the `cat` command:

Example:
```
$ cat /etc/apache2/sites-enabled/000-default.conf
```

Copy and paste the full/exact output, example shown below. Please surround any output with Markdown code fences so the results are legible ([reference this post for examples](https://github.com/susanBuck/e2-fall19/issues/2)).

Please also examine/share the output of your server's Apache error log with the following command:
```
cat /var/log/apache2/error.log
```

**Comment by susanBuck** [comment] 2019-11-18 23:04
Other things I thought of:

1. Is your e2 repo up to date? Looks like the last commit was 6 days ago. Commit/push any changes from local and then pull those changes to production, ensuring it has the most up to date code.

2. Confirm you've run `composer install --no-dev` in the root of your `zipfoods` project on your server so that all of your dependencies are updated and in sync w/ local.

**Comment by nbandach** [comment] 2019-11-19 17:25
Last login: Mon Nov 18 21:11:33 on ttys002

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
Natalias-MacBook-Air:~ natbandach$ ssh root@104.248.204.1
Welcome to Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Tue Nov 19 17:23:50 UTC 2019

  System load:  0.0               Processes:           97
  Usage of /:   9.5% of 24.06GB   Users logged in:     0
  Memory usage: 36%               IP address for eth0: 104.248.204.1
  Swap usage:   0%

 * Canonical Livepatch is available for installation.
   - Reduce system reboots and improve kernel security. Activate at:
     https://ubuntu.com/livepatch

59 packages can be updated.
7 updates are security updates.


*** System restart required ***
********************************************************************************

Welcome to DigitalOcean's One-Click LAMP Droplet. 
To keep this Droplet secure, the UFW firewall is enabled. 
All ports are BLOCKED except 22 (SSH), 80 (HTTP), and 443 (HTTPS).

In a web browser, you can view:
 * The LAMP One-Click Quickstart guide: http://do.co/lamp1804#start
 * Your LAMP website: http://104.248.204.1

On the server:
 * The default web root is located at /var/www/html
 * The MySQL root password is saved in /root/.digitalocean_password
 * Certbot is preinstalled. Run it to configure HTTPS. See
   http://do.co/lamp1804#enable-https for more detail.

For help and more information, visit http://do.co/lamp1804

********************************************************************************
To delete this message of the day: rm -rf /etc/update-motd.d/99-one-click
Last login: Mon Nov 18 19:58:31 2019 from 88.26.147.114
root@e2:~# cat /etc/apache2/sites-enabled/000-default.conf
<VirtualHost *:80>
        ServerAdmin webmaster@localhost
        DocumentRoot /var/www/html

        <Directory /var/www/html/>
            Options Indexes FollowSymLinks
            AllowOverride All
            Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log
        CustomLog ${APACHE_LOG_DIR}/access.log combined

        <IfModule mod_dir.c>
            DirectoryIndex index.php index.pl index.cgi index.html index.xhtml index.htm
        </IfModule>

</VirtualHost>
<VirtualHost *:80>
  ServerName practice.natbandach.me
  DocumentRoot "/var/www/html/e2/practice"
  <Directory "/var/www/html/e2/practice">
    AllowOverride All
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName p1.natbandach.me
  DocumentRoot "/var/www/html/e2/p1"
  <Directory "/var/www/html/e2/p1">
    AllowOverride All
  </Directory>
</VirtualHost>


<VirtualHost *:80>
  ServerName p2.natbandach.me
  DocumentRoot "/var/www/html/e2/p2"
  <Directory "/var/www/html/e2/p2">
    AllowOverride All
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName practice.natbandach.me
  DocumentRoot "/var/www/html/e2/practice"
  <Directory "/var/www/html/e2/practice">
    AllowOverride All
  </Directory>
</VirtualHost>

<VirtualHost *:80>
  ServerName p3.natbandach.me
  DocumentRoot "/var/www/html/e2/p3"
  <Directory "/var/www/html/e2/p3">
    AllowOverride All
  </Directory>
</VirtualHost>

<VirtualHost *:80>
    ServerName zipfoods.natbandach.me
    DocumentRoot /var/www/html/e2/zipfoods/public
    <Directory /var/www/html/e2/zipfoods/public>
        Options Indexes FollowSymLinks MultiViews
        AllowOverride All
        Order allow,deny
        allow from all
        Require all granted
    </Directory>
</VirtualHost>

root@e2:~#

**Comment by nbandach** [comment] 2019-11-19 17:28
Did the commit, still not working..
![Screenshot 2019-11-19 at 18 28 36](https://user-images.githubusercontent.com/6833462/69170476-6cb31980-0afa-11ea-887c-1bbf6540a39f.png)

**Comment by susanBuck** [comment] 2019-11-19 20:27
**Note 1**
I updated your last post with Markdown code fences so the results are legible. Please do this when sharing output in future posts. It's really hard to skim through verbose code and command line output when it's not correctly formatted.

**Note 2**
Did you notice that when you ran `composer install --no-dev` it was not successful?
```
root@e2:/var/www/html/e2# composer install --no-dev
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /var/www/html/e2
```

Looking at the feedback it gives you and reiterating my instructions above (`Confirm you've run composer install --no-dev in the root of your zipfoods project`) please try this again.


**Note 3**
Also, above I said:
> Please also examine/share the output of your server's Apache error log with the following command:

> $ cat /var/log/apache2/error.log

Please include the results of this in your next reply.

**Comment by nbandach** [comment] 2019-11-19 22:09
Hi Susan, thanks a lot for this:

Replying to your notes:

**Note 1**: 

Thanks. I will try to use them from now on.

**Note 2**:
![Screenshot 2019-11-19 at 22 55 11](https://user-images.githubusercontent.com/6833462/69190504-d3e3c480-0b20-11ea-9f6e-7151198b16f3.png)

**Note 3**:
`root@e2:/var/www/html/e2/zipfoods# cat /var/log/apache2/error.log
[Tue Nov 19 06:25:01.801489 2019] [mpm_prefork:notice] [pid 30409] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Tue Nov 19 06:25:01.801538 2019] [core:notice] [pid 30409] AH00094: Command line: '/usr/sbin/apache2'
[Tue Nov 19 17:27:46.146340 2019] [php7:error] [pid 32318] [client 2.139.150.93:49956] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php:22\nStack trace:\n#0 /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(54): E2\\Database->__construct(NULL, 'myapp', 'root', NULL, 'utf8mb4')\n#1 /var/www/html/e2/zipfoods/public/index.php(12): E2\\App->__construct()\n#2 {main}\n  thrown in /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php on line 22
[Tue Nov 19 17:28:29.415742 2019] [php7:error] [pid 32316] [client 2.139.150.93:49974] PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php:22\nStack trace:\n#0 /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/App.php(54): E2\\Database->__construct(NULL, 'myapp', 'root', NULL, 'utf8mb4')\n#1 /var/www/html/e2/zipfoods/public/index.php(12): E2\\App->__construct()\n#2 {main}\n  thrown in /var/www/html/e2/zipfoods/vendor/susanbuck/e2core/src/Database.php on line 22
root@e2:/var/www/html/e2/zipfoods# 
`

**Comment by susanBuck** [comment] 2019-11-19 23:21
Hi Nat -

Just tested <http://zipfoods.natbandach.me> and it's now loading.

**Running `composer install --no-dev` is what fixed it.** As you can see from the output, this command updated (amongst other dependencies) the e2core from version 0.1.3 to 0.1.5. 

The older version of e2core was automatically attempting to connect to a database and it threw an error when it couldn't connect. There's evidence of this in the output you shared from the error log file:

```
PHP Fatal error: Uncaught PDOException: SQLSTATE[HY000] [1698] Access denied for user 'root'@'localhost' in
```

The updated version of e2core only attempts to connect if you invoke the connection. This prevents it from connecting to a database that might not yet be set up, as is the case on production.

[Here's a refresher on the deployment process once you're using a Composer managed app...](https://hesweb.dev/e2/notes#/php/composer-deployment?jump=deploy)

It comes down to two steps:
1. Pull the latest changes from Github
2. Run `composer install --no-dev` to update dependencies

**Comment by susanBuck** [comment] 2019-11-20 02:29
Closing this thread as I believe the issue is resolved, but feel free to re-open if it's not functioning on your end, or start a new thread if some other issue is occuring.

**Closed by susanBuck** 2019-11-20 02:29 UTC
